### ISSUE TITLE
Fix Textual Inversion pre-trained weights to CLIP model

### ISSUE THREAD

**Issue by Flu0XeT1n** [brandontrabucco/da-fusion#10]
Hi, it's me again.
When I go though your code, I find you directly fix the pre-trained textual inversion weights to the CLIP model in your implementation. Why? By intuition, the weights from Textual Inversion and those from CLIP should not be in the same space. Should there be an MLP to transform these weights to the same space? Forgive my foolishness, I am still new in this area.
![image](https://github.com/brandontrabucco/da-fusion/assets/56498265/91a489b5-3e92-4014-9c19-2ab6869be2bb)

**Comment by brandontrabucco** [comment]
Hello [Flu0XeT1n](https://github.com/Flu0XeT1n),

Thanks for following up again, Textual Inversion generates new token embeddings in the CLIP text embedding space. [These lines](https://github.com/brandontrabucco/da-fusion/blob/main/fine_tune.py#L510) from the textual inversion script we provide showcase which embeddings are used. More details can be found in the [original paper](https://arxiv.org/abs/2208.01618) by Gal et al. 2022 if you're interested. The line you marked with a `TODO` in the image you shared corresponds with [this line](https://github.com/brandontrabucco/da-fusion/blob/main/fine_tune.py#L512) in the training script.

No additional maps on top of the new tokens are needed for Textual Inversion.

-Brandon
