### ISSUE TITLE
FileNotFoundError: pascal-0-4.pt

### ISSUE THREAD

**Issue by JiaojiaoYe1994** [brandontrabucco/da-fusion#17]
Hi all, I have met the following error when I try to train image classification models using augmented images from DA-Fusion, anyone has the same issue? The execution code is:

> ` python train_classifier.py --logdir pascal-baselines/textual-inversion-0.5 --synthetic-dir "aug/textual-inversion-0.5/{dataset}-{seed}-{examples_per_class}" --dataset pascal --prompt "a photo of a {name}" --aug textual-inversion --guidance-scale 7.5 --strength 0.5 --mask 0 --inverted 0 --num-synthetic 10 --synthetic-probability 0.5 --num-trials 1 --examples-per-class 4
`

The returned error:
`FileNotFoundError: [Errno 2] No such file or directory: 'pascal-tokens/pascal-0-4.pt'`

**Comment by brandontrabucco** [comment]
Hello [JiaojiaoYe1994](https://github.com/JiaojiaoYe1994),

These are tokens from textual inversion, and can be obtained by fine-tuning Stable Diffusion using `fine_tune_upstream.py`. I'll upload the tokens I obtained when writing the paper in a Google Drive link and post it here.

**Comment by zhixiongzh** [comment]
> Hello [JiaojiaoYe1994](https://github.com/JiaojiaoYe1994),
> 
> These are tokens from textual inversion, and can be obtained by fine-tuning Stable Diffusion using `fine_tune_upstream.py`. I'll upload the tokens I obtained when writing the paper in a Google Drive link and post it here.

Hi @brandontrabucco,

what would be the main difference between `fine_tune.py` and `fine_tune_upstream.py`, it seems like `upstream` support running different class_names in parallel, which is good, but is there other differences?

**Comment by zhl95** [comment]
Hi @JiaojiaoYe1994 @brandontrabucco  could you help share the cmd to generate the tokens?
