### ISSUE TITLE
Where can I get the full info code

### ISSUE THREAD

**Issue by theplace75** [brandontrabucco/da-fusion#23]
Thanks for wonderful project.
 I would appreciate it if you could provide it. Thank you

**Comment by brandontrabucco** [comment]
Hello [theplace75](https://github.com/theplace75),

Thanks for your interest in our work!

I'm working on a public release of the code for the latest results in our ICLR paper. I'm planning to release it in the next few weeks, and I'm happy to be a resource for you in the meantime. The current code fine-tunes tokens and generates augmentations for a subset of the datasets (these were the focus in an earlier draft of the manuscript), what additional information can I help with?

The public release adds the new datasets in our paper, and better hyperparameters (see the appendix):
https://openreview.net/pdf?id=ZWzUA9zeAg

-Brandon

**Comment by theplace75** [comment]
I understand.

In the fine_tune.py script, replacing the line at 785 where args.initializer_token is set to "the" with the formatted classname as the initializer token was the method proposed in the paper for conducting the experiment shown in Figure 5: Few-shot classification performance with full information.

Thank you for your kind response. If there's any mistake in my understanding, I would appreciate your correction.

-Chae-
