### ISSUE TITLE
Increasing number of images with your augmentation

### ISSUE THREAD

**Issue by khawar-islam** [brandontrabucco/da-fusion#30]
Dear @brandontrabucco @KellyYutongHe 

Thanks for your work. For instance, I have class that contains 10 images, when i augment class based on your augmentation technique. Does it increase the number of images in from 10 to 20 or it remains same?

Regards,
Khawar

**Comment by vaventt** [comment]
Hi

You can control the number of generated images for each real image with the `--num-synthetic` parameter in `generate_augmentations.py` or `train_classifier.py`. In their research, the authors generated 10 images per real image for PascalVOC/COCO datasets, and 50 images per real image for the LeafySpurge dataset. Below is an example of their script:

```
python train_classifier.py --logdir pascal-baselines/textual-inversion-1.0-0.75-0.5-0.25 \
--synthetic-dir "/projects/rsalakhugroup/btrabucc/aug/\
textual-inversion-1.0-0.75-0.5-0.25/{dataset}-{seed}-{examples_per_class}" \
--dataset pascal --prompt "a photo of a {name}" \
--aug textual-inversion textual-inversion textual-inversion textual-inversion \
--guidance-scale 7.5 7.5 7.5 7.5 \
--strength 1.0 0.75 0.5 0.25 \
--mask 0 0 0 0 \
--inverted 0 0 0 0 \
--probs 0.25 0.25 0.25 0.25 \
--compose parallel --num-synthetic 10 --synthetic-probability 0.5 \
--num-trials 8 --examples-per-class 1 2 4 8 16

```
