### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by Sreyan88** [brandontrabucco/da-fusion#7]
Hi there!

Great repo and great work! I encountered an error while installing:

When I do this: `pip install -e da-fusion`

It throws this error:

`ERROR: da-fusion is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).`

**Comment by brandontrabucco** [comment]
Hello [Sreyan88](https://github.com/Sreyan88),

calling `pip install -e /path/to/da-fusion`

will install the directory `/path/to/da-fusion` as a python package. Can you confirm the directory exists and which folder your terminal is in when you are installing?

**Comment by Sreyan88** [comment]
Yes sorry for the confusion I did cd before running the command by mistake!
